# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(613, 328)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.createdByLabel = QtWidgets.QLabel(self.centralwidget)
        self.createdByLabel.setGeometry(QtCore.QRect(20, 50, 101, 16))
        self.createdByLabel.setObjectName("createdByLabel")
        self.creator = QtWidgets.QLabel(self.centralwidget)
        self.creator.setGeometry(QtCore.QRect(130, 50, 111, 17))
        self.creator.setObjectName("creator")
        self.githubLabel = QtWidgets.QLabel(self.centralwidget)
        self.githubLabel.setGeometry(QtCore.QRect(20, 70, 91, 17))
        self.githubLabel.setObjectName("githubLabel")
        self.github = QtWidgets.QLabel(self.centralwidget)
        self.github.setGeometry(QtCore.QRect(120, 70, 121, 17))
        self.github.setObjectName("github")
        self.instagramLabel = QtWidgets.QLabel(self.centralwidget)
        self.instagramLabel.setGeometry(QtCore.QRect(20, 90, 91, 17))
        self.instagramLabel.setObjectName("instagramLabel")
        self.instagram = QtWidgets.QLabel(self.centralwidget)
        self.instagram.setGeometry(QtCore.QRect(120, 90, 121, 17))
        self.instagram.setObjectName("instagram")
        self.twitterLabel = QtWidgets.QLabel(self.centralwidget)
        self.twitterLabel.setGeometry(QtCore.QRect(20, 110, 91, 17))
        self.twitterLabel.setObjectName("twitterLabel")
        self.twitter = QtWidgets.QLabel(self.centralwidget)
        self.twitter.setGeometry(QtCore.QRect(120, 110, 101, 17))
        self.twitter.setObjectName("twitter")
        self.aboutLabel = QtWidgets.QLabel(self.centralwidget)
        self.aboutLabel.setGeometry(QtCore.QRect(280, 20, 41, 17))
        self.aboutLabel.setObjectName("aboutLabel")
        self.anim = QtWidgets.QLabel(self.centralwidget)
        self.anim.setGeometry(QtCore.QRect(360, 60, 211, 181))
        self.anim.setObjectName("anim")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 613, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.createdByLabel.setText(_translate("MainWindow", "Created By :"))
        self.creator.setText(_translate("MainWindow", "Somnath Das"))
        self.githubLabel.setText(_translate("MainWindow", "Github :"))
        self.github.setText(_translate("MainWindow", "@SomnathDas"))
        self.instagramLabel.setText(_translate("MainWindow", "Instagram :"))
        self.instagram.setText(_translate("MainWindow", "@samurai3247"))
        self.twitterLabel.setText(_translate("MainWindow", "Twitter :"))
        self.twitter.setText(_translate("MainWindow", "@aksd3247"))
        self.aboutLabel.setText(_translate("MainWindow", "About"))
        self.anim.setText(_translate("MainWindow", "Anim"))
